[default]
description = "Default permissions for the plugin"
permissions = ["allow-register-function", "allow-call-function", "allow-read-variable"]
# "allow-run-python" is not enabled by default for security reasons
